name: ARM template deploy

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: GitHub properties
        run: |
          echo CI: $CI
          echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
          echo GITHUB_RUN_ID: $GITHUB_RUN_ID
          echo GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
          echo GITHUB_ACTION: $GITHUB_ACTION
          echo GITHUB_ACTIONS: $GITHUB_ACTIONS
          echo GITHUB_ACTOR: $GITHUB_ACTOR
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
          echo GITHUB_SHA: $GITHUB_SHA
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          echo GITHUB_API_URL: $GITHUB_API_URL
          echo GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL
          echo github.action_path: $github.action_path

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Validate Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        id: armdeploy
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: szkchmzad2
          template: azuredeploy.json
          parameters: azuredeploy.parameters.json
          deploymentMode: Validate #Complete  # Validate
      
      - name: ARM output
        run: |
          echo ${{ steps.armdeploy.outputs.testoutput }}

      - name: GitHub properties
        run: |
          echo CI: $CI
          echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
          echo GITHUB_RUN_ID: $GITHUB_RUN_ID
          echo GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
          echo GITHUB_ACTION: $GITHUB_ACTION
          echo GITHUB_ACTIONS: $GITHUB_ACTIONS
          echo GITHUB_ACTOR: $GITHUB_ACTOR
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
          echo GITHUB_SHA: $GITHUB_SHA
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          echo GITHUB_API_URL: $GITHUB_API_URL
          echo GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL
          echo github.action_path: $github.action_path
