name: ARM template deploy

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        id: ARMValidate
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: szkchmzad2
          template: azuredeploy.json
          parameters: azuredeploy.parameters.json
          deploymentMode: Validate
      
      - name: Deploy Azure Resource Manager (ARM) Template
        if: ${{ env.GITHUB_REF == 'refs/heads/master' }} 
        uses: Azure/arm-deploy@v1
        id: ARMDeploy
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: szkchmzad2
          template: azuredeploy.json
          parameters: azuredeploy.parameters.json
          deploymentMode: Complete

      - name: ARM output
        run: |
          echo ${{ steps.ARMDeploy.outputs.testoutput }}